
env:
  CONFIG: config.sh
  
  CIRRUS_SHELL: bash

task:
  name: Recovery Build
  timeout_in: 120m
  container:
    image: openjdk:latest
    cpu: 8
    memory: 20G
  Build_script:
    - curl -sL
      https://raw.githubusercontent.com/Sanju0910/PitchBlack-CI/main/build.sh | bash
      
  Release_build:
    name: Release Builds
    run: |
      sudo apt-get update && sudo apt-get install sshpass -y
      cd $BuildPath 
      bash vendor/utils/pb_deploy.sh ${BUILD_RELEASE_TYPE} ${VENDOR} ${CODENAME}
